#!/usr/bin/env ruby
require 'fileutils'

puts "Compiling simulator..."
system("tsc --noImplicitAny test/simulate.ts") || exit(false)

puts "Running simulator..."
Dir.entries('test/fixtures/simulations').each do |dir|
  next if dir[0] == '.'
  puts dir

  expected_path = "test/fixtures/simulations/#{dir}/expected.txt"
  actual_path = "test/fixtures/simulations/#{dir}/actual.txt"
  unless File.directory?("test/fixtures/simulations/#{dir}")
    FileUtils.mkdir_p("test/fixtures/simulations/#{dir}")
  end
  actual = `node test/simulate.js #{dir}`
  puts "Comparing outputs..."
  File.write(actual_path, actual)
  expected = File.exists?(expected_path) ? File.read(expected_path) : ""
  if actual != expected
    puts "ERROR"
    puts actual_path
    exit(false)
  end
end

puts "All simulation tests passed"
