#!/usr/bin/env ruby
`tsc index.ts`

# expected_path = "simulation_tests/line/expected.txt"
actual_path = "simulation_tests/line/actual.txt"

actual = `node simulate.js line`
# expected = File.read(expected_path)

# if actual != expected
  File.write(actual_path, actual)
# end
puts actual_path

# puts `diff #{expected_path} #{actual_path}`